apiVersion: v1
kind: Service
metadata:
  name: {{ include "mlops-stack.fullname" . }}-airflow-webserver
spec:
  type: ClusterIP  # or NodePort/LoadBalancer if you prefer, or make it configurable
  selector:
    app: {{ include "mlops-stack.fullname" . }}-airflow-webserver
  ports:
    - name: http
      port: 8080
      targetPort: 8080
