apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "mlops-stack.fullname" . }}-minio-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.minio.persistence.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.minio.persistence.size }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mlops-stack.fullname" . }}-minio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "mlops-stack.fullname" . }}-minio
  template:
    metadata:
      labels:
        app: {{ include "mlops-stack.fullname" . }}-minio
    spec:
      nodeSelector:
{{- toYaml .Values.global.storageNodeSelector | nindent 8 }}
      containers:
        - name: minio
          image: {{ .Values.minio.image }}
          args:
            - "server"
            - "/data"
            - "--console-address=:{{ .Values.minio.service.consolePort }}"
          env:
            - name: MINIO_ROOT_USER
              value: {{ .Values.minio.rootUser | quote }}
            - name: MINIO_ROOT_PASSWORD
              value: {{ .Values.minio.rootPassword | quote }}
          ports:
            - containerPort: {{ .Values.minio.service.port }}
            - containerPort: {{ .Values.minio.service.consolePort }}
          volumeMounts:
            - name: data
              mountPath: /data
          livenessProbe:
            httpGet:
              path: /minio/health/ready
              port: {{ .Values.minio.service.port }}
            initialDelaySeconds: 20
            periodSeconds: 10
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "mlops-stack.fullname" . }}-minio-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "mlops-stack.fullname" . }}-minio
spec:
  type: {{ .Values.minio.service.type }}
  selector:
    app: {{ include "mlops-stack.fullname" . }}-minio
  ports:
    - name: api
      port: {{ .Values.minio.service.port }}
      targetPort: {{ .Values.minio.service.port }}
    - name: console
      port: {{ .Values.minio.service.consolePort }}
      targetPort: {{ .Values.minio.service.consolePort }}
