apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mlops-stack.fullname" . }}-mlflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "mlops-stack.fullname" . }}-mlflow
  template:
    metadata:
      labels:
        app: {{ include "mlops-stack.fullname" . }}-mlflow
    spec:
      containers:
        - name: mlflow
          image: "{{ .Values.mlflow.image.repository }}:{{ .Values.mlflow.image.tag }}"
          env:
            - name: MLFLOW_S3_ENDPOINT_URL
              value: {{ .Values.mlflow.artifactStore.s3Endpoint | quote }}
            - name: AWS_ACCESS_KEY_ID
              value: {{ .Values.mlflow.artifactStore.awsAccessKeyId | quote }}
            - name: AWS_SECRET_ACCESS_KEY
              value: {{ .Values.mlflow.artifactStore.awsSecretAccessKey | quote }}
          args:
            - "mlflow"
            - "server"
            - "--backend-store-uri"
            - "postgresql+psycopg2://{{ .Values.mlflowDb.user }}:{{ .Values.mlflowDb.password }}@{{ include "mlops-stack.fullname" . }}-mlflow-db:5432/{{ .Values.mlflowDb.dbName }}"
            - "--default-artifact-root"
            - "s3://{{ .Values.mlflow.artifactStore.bucket }}/"
            - "--host"
            - "0.0.0.0"
            - "--port"
            - "{{ .Values.mlflow.service.port }}"
          ports:
            - containerPort: {{ .Values.mlflow.service.port }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "mlops-stack.fullname" . }}-mlflow
spec:
  type: {{ .Values.mlflow.service.type }}
  selector:
    app: {{ include "mlops-stack.fullname" . }}-mlflow
  ports:
    - port: {{ .Values.mlflow.service.port }}
      targetPort: {{ .Values.mlflow.service.port }}
