apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.apps.yml -o komposefiles/ --volumes hostPath
    kompose.version: "b0d978a"
  labels:
    io.kompose.service: api
  name: api
  namespace: apps
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: api
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.apps.yml -o komposefiles/ --volumes hostPath
        kompose.version: "b0d978a"
      labels:
        io.kompose.service: api
    spec:
      containers:
        - env:
            - name: AWS_ACCESS_KEY_ID
              value: admin
            - name: AWS_SECRET_ACCESS_KEY
              value: adminadmin
            - name: MLFLOW_S3_ENDPOINT_URL
              value: http://minio:9000
            - name: MLFLOW_TRACKING_URI
              value: http://mlflow:5000
            - name: MODEL_NAME
              value: diabetic_risk_model
          image: aalbuez/mlops-prediction-api:main-b0d978a
          name: mlops-prediction-api
          ports:
            - containerPort: 8000
              protocol: TCP
      restartPolicy: Always
