apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.apps.yml -o komposefiles/ --volumes hostPath
    kompose.version: "021687c"
  labels:
    io.kompose.service: streamlit
  name: streamlit
  namespace: apps
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: streamlit
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.apps.yml -o komposefiles/ --volumes hostPath
        kompose.version: "021687c"
      labels:
        io.kompose.service: streamlit
    spec:
      containers:
        - env:
            - name: API_BASE_URL
              value: http://api:8000
          image: aalbuez/mlops-prediction-ui:main-021687c
          name: mlops-prediction-ui
          ports:
            - containerPort: 8501
              protocol: TCP
      restartPolicy: Always
