apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../docker-compose.kompose.yml --namespace apps
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: streamlit
  name: streamlit
  namespace: apps
spec:
  ports:
    - name: "8501"
      port: 8501
      targetPort: 8501
  selector:
    io.kompose.service: streamlit