services:
  api:
    build: ./api
    container_name: final-api
    ports:
      - "8000:8000"
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000
      - MLFLOW_S3_ENDPOINT_URL=http://minio:9000
      - AWS_ACCESS_KEY_ID=${MINIO_ROOT_USER:-admin}
      - AWS_SECRET_ACCESS_KEY=${MINIO_ROOT_PASSWORD:-adminadmin}
      - MODEL_NAME=real_estate_rf
    networks:
      - projecto-final_default
    restart: unless-stopped

  streamlit:
    build: ./streamlit
    container_name: final-streamlit
    ports:
      - "8501:8501"
    environment:
      - API_BASE_URL=http://api:8000
    networks:
      - projecto-final_default
    depends_on:
      - api
    restart: unless-stopped

networks:
  projecto-final_default:
    external: true
    name: projecto-final_projecto-final_default
